-- 1
SELECT * FROM ZESPOLY;
-- 2
SELECT * FROM PRACOWNICY;
-- 3
SELECT NAZWISKO, PLACA_POD*12 FROM PRACOWNICY;
-- 4
SELECT ETAT, PLACA_POD+PLACA_DOD AS MIESIECZNE_ZAROBKI FROM PRACOWNICY;
-- 5
SELECT * FROM ZESPOLY ORDER BY NAZWA;
-- 6
SELECT DISTINCT ETAT FROM PACOWNICY;
-- 7
SELECT * FROM PACOWNICY WHERE ETAT='ASYSTENT';
-- 8
SELECT ID_PRAC, NAZWISKO, ETAT, PLACA_POD, ID_ZESP
FROM PRACOWNICY
WHERE ID_ZESP=30 OR ID_ZESP=40
ORDER BY PLACA_POD DESC;
-- 9
SELECT NAZWISKO, ID_ZESP, PLACA_POD
FROM PRACOWNICY
WHERE PLACA_POD BETWEEN 300 AND 800;
-- 10
SELECT NAZWISKO, ID_ZESP, ETAT
FROM PRACOWNICY
WHERE NAZWISKO LIKE '%SKI';
-- 11
SELECT ID_PRAC, ID_SZEFA, NAZWISKO
FROM PRACOWNICY 
WHERE PLACA_POD > 1000 AND ID_SZEFA IS NOT NULL;
-- 12
SELECT NAZWISKO, ID_ZESP
FROM PRACOWNICY
WHERE (NAZWISKO LIKE 'M%' OR NAZWISKO LIKE '%SKI') AND ID_ZESP=20;
-- 13
-- ORACLE VERSION
SELECT NAZWISKO, ETAT, (PLACA_POD+NVL(PLACA_DOD, 0))/160 AS STAWKA
FROM PRACOWNICY
WHERE ETAT!='ADIUNKT' AND ETAT!='ASYSTENT' AND ETAT!='STAZYSTA'
ORDER BY STAWKA;
-- MYSQL VERSION
SELECT NAZWISKO, ETAT, (PLACA_POD+COALESCE(PLACA_DOD, 0))/160 AS STAWKA
FROM PRACOWNICY
WHERE ETAT!='ADIUNKT' AND ETAT!='ASYSTENT' AND ETAT!='STAZYSTA'
ORDER BY STAWKA;
-- COALESCE() = NVL()
-- 14
SELECT NAZWISKO, ETAT, PLACA_POD, PLACA_DOD
FROM PRACOWNICY
WHERE (PLACA_POD+COALESCE(PLACA_DOD, 0)) > 1000
ORDER BY ETAT ASC, NAZWISKO ASC;
-- 15
-- MYSQL VERSION
SELECT CONCAT(NAZWISKO,' PRACUJE OD ', ZATRUDNIONY, ' I ZARABIA ', PLACA_POD) AS PROFESOROWIE
FROM PRACOWNICY
WHERE ETAT='PROFESOR'
ORDER BY PLACA_POD DESC;

-- ORACLE VERSION
SELECT NAZWISKO||' PRACUJE OD '|| ZATRUDNIONY|| ' I ZARABIA '|| PLACA_POD) AS PROFESOROWIE
FROM PRACOWNICY
WHERE ETAT='PROFESOR'
ORDER BY PLACA_POD DESC;