-- 1
SELECT MAX(PLACA_POD) AS MAXIMUM,
  MIN(PLACA_POD) AS MINIMUM,
  MAX(PLACA_POD)-MIN(PLACA_POD) AS ROZNICA
FROM PRACOWNICY;
-- 2
SELECT ETAT, AVG(PLACA_POD) AS SREDNIA
FROM PRACOWNICY
GROUP BY ETAT
ORDER BY SREDNIA DESC;
-- 3
SELECT COUNT(ETAT) AS PROFESOROWIE
FROM PRACOWNICY
WHERE ETAT='PROFESOR';
-- 4
SELECT ID_ZESP,
  SUM(PLACA_POD+COALESCE(PLACA_DOD,0))
FROM PRACOWNICY
GROUP BY ID_ZESP;
-- 5
SELECT SUM(PLACA_POD+COALESCE(PLACA_DOD,0)) AS MAXIMUM
FROM PRACOWNICY
GROUP BY ID_ZESP
ORDER BY MAXIMUM DESC
LIMIT 1;

-- or

SELECT MAX(SUM(PLACA_POD+NVL(PLACA_DOD, 0))) AS MAXI FROM PRACOWNICY
GROUP BY ID_ZESP;

-- 6
SELECT ID_SZEFA, MIN(PLACA_POD) AS MIN
FROM PRACOWNICY
GROUP BY ID_SZEFA
ORDER BY MIN DESC;

-- 7
SELECT ID_ZESP, COUNT(ID_PRAC)
FROM PRACOWNICY
GROUP BY ID_ZESP
ORDER BY COUNT(ID_PRAC) DESC;

-- 8
SELECT ID_ZESP, COUNT(ID_PRAC)
FROM PRACOWNICY
GROUP BY ID_ZESP
HAVING COUNT(ID_PRAC)>3
ORDER BY COUNT(ID_PRAC) DESC;

-- 9
SELECT ID_PRAC, COUNT(ID_PRAC)
FROM PRACOWNICY
GROUP BY ID_PRAC
HAVING COUNT(ID_PRAC)>1;

-- 10
SELECT ETAT, COUNT(PLACA_POD), SUM(PLACA_POD)
FROM PRACOWNICY
WHERE EXTRACT(YEAR FROM ZATRUDNIONY)<1990
GROUP BY ETAT;

-- 11
SELECT 
	ID_ZESP, 
	ETAT, 
	ROUND(AVG(PLACA_POD+NVL(PLACA_DOD, 0)), 0), 
	ROUND(MAX(PLACA_POD+NVL(PLACA_DOD, 0)), 0)
FROM PRACOWNICY
WHERE ETAT='PROFESOR' OR ETAT='ASYSTENT'
GROUP BY ID_ZESP, ETAT
ORDER BY ID_ZESP;

-- 12
SELECT EXTRACT(YEAR FROM ZATRUDNIONY) AS ROK, COUNT(*)
FROM PRACOWNICY
GROUP BY EXTRACT(YEAR FROM ZATRUDNIONY)
ORDER BY ROK;

-- 13
SELECT LENGTH(NAZWISKO) AS ILE_LITER, COUNT(*)
FROM PRACOWNICY
GROUP BY LENGTH(NAZWISKO)
ORDER BY ILE_LITER;

-- 14
SELECT COUNT(NAZWISKO)
FROM PRACOWNICY
WHERE NAZWISKO LIKE '%E%' OR NAZWISKO LIKE '%e%';