-- 1
SELECT MAX(PLACA_POD) AS MAXIMUM,
  MIN(PLACA_POD) AS MINIMUM,
  MAX(PLACA_POD)-MIN(PLACA_POD) AS ROZNICA
FROM PRACOWNICY;
-- 2
SELECT ETAT, AVG(PLACA_POD) AS SREDNIA
FROM PRACOWNICY
GROUP BY ETAT
ORDER BY SREDNIA DESC;
-- 3
SELECT COUNT(ETAT) AS PROFESOROWIE
FROM PRACOWNICY
WHERE ETAT='PROFESOR';
-- 4
SELECT ID_ZESP,
  SUM(PLACA_POD+COALESCE(PLACA_DOD,0))
FROM PRACOWNICY
GROUP BY ID_ZESP;
-- 5
SELECT SUM(PLACA_POD+COALESCE(PLACA_DOD,0)) AS MAXIMUM
FROM PRACOWNICY
GROUP BY ID_ZESP
ORDER BY MAXIMUM DESC
LIMIT 1;
-- 6
SELECT ID_SZEFA, MIN(PLACA_POD) AS MIN
FROM PRACOWNICY
GROUP BY ID_SZEFA
ORDER BY MIN DESC;