-- 1
SELECT PRACOWNICY.NAZWISKO, 
  PRACOWNICY.ETAT, PRACOWNICY.ID_ZESP,
  ZESPOLY.NAZWA
FROM PRACOWNICY
JOIN ZESPOLY
WHERE PRACOWNICY.ID_ZESP=ZESPOLY.ID_ZESP;
-- 2
SELECT PRACOWNICY.NAZWISKO, PRACOWNICY.ETAT,
  PRACOWNICY.ID_ZESP, ZESPOLY.ADRES
FROM PRACOWNICY
JOIN ZESPOLY
ON PRACOWNICY.ID_ZESP=ZESPOLY.ID_ZESP
WHERE ZESPOLY.ADRES='PIOTROWO 3A'
ORDER BY PRACOWNICY.NAZWISKO;
-- 3
SELECT PRACOWNICY.NAZWISKO, ZESPOLY.ADRES, ZESPOLY.NAZWA
FROM PRACOWNICY
JOIN ZESPOLY
ON PRACOWNICY.ID_ZESP=ZESPOLY.ID_ZESP
WHERE PRACOWNICY.PLACA_POD>400;
-- 4
SELECT PRACOWNICY.NAZWISKO, PRACOWNICY.PLACA_POD,
  ETATY.NAZWA, ETATY.PLACA_MIN, ETATY.PLACA_MAX
FROM PRACOWNICY
JOIN ETATY
ON ETATY.NAZWA=PRACOWNICY.ETAT;
-- 5
SELECT PRACOWNICY.NAZWISKO, PRACOWNICY.PLACA_POD, 
  PRACOWNICY.ETAT, ETATY.NAZWA, 
  ETATY.PLACA_MIN, ETATY.PLACA_MAX
FROM PRACOWNICY
JOIN ETATY
ON ETATY.NAZWA='SEKRETARKA'
WHERE PRACOWNICY.PLACA_POD<ETATY.PLACA_MAX 
AND PRACOWNICY.PLACA_POD>ETATY.PLACA_MIN;
-- 6
SELECT PRACOWNICY.NAZWISKO, PRACOWNICY.ETAT, 
  PRACOWNICY.PLACA_POD, ZESPOLY.NAZWA
FROM PRACOWNICY
JOIN ZESPOLY
ON PRACOWNICY.ID_ZESP=ZESPOLY.ID_ZESP
WHERE PRACOWNICY.ETAT!='ASYSTENT'
ORDER BY PRACOWNICY.PLACA_POD DESC;
-- 7
SELECT PRACOWNICY.NAZWISKO, PRACOWNICY.ETAT, 
  PRACOWNICY.PLACA_POD*12 + COALESCE(PRACOWNICY.PLACA_DOD,0) AS ROCZNA_PLACA, 
  ETATY.NAZWA, ZESPOLY.NAZWA
FROM PRACOWNICY
JOIN ZESPOLY ON ZESPOLY.ID_ZESP=PRACOWNICY.ID_ZESP
JOIN ETATY ON ETATY.NAZWA=PRACOWNICY.ETAT
WHERE PRACOWNICY.PLACA_POD*12 + COALESCE(PRACOWNICY.PLACA_DOD,0) >5500;
-- 8
SELECT p.ID_PRAC, p.NAZWISKO, sz.ID_PRAC, sz.NAZWISKO
FROM PRACOWNICY p
JOIN PRACOWNICY sz ON p.ID_SZEFA=sz.ID_PRAC;
-- 9
SELECT p.ID_PRAC, p.NAZWISKO, sz.ID_PRAC, sz.NAZWISKO
FROM PRACOWNICY p
LEFT JOIN PRACOWNICY sz ON p.ID_SZEFA=sz.ID_PRAC;
-- 10
SELECT ZESPOLY.NAZWA, COUNT(ZESPOLY.ID_ZESP) AS LICZBA,
  AVG(PRACOWNICY.PLACA_POD)
FROM ZESPOLY
JOIN PRACOWNICY
ON ZESPOLY.ID_ZESP=PRACOWNICY.ID_ZESP
GROUP BY ZESPOLY.NAZWA;
-- 11
SELECT sz.NAZWISKO, COUNT(sz.ID_PRAC) AS LICZBA
FROM PRACOWNICY sz
JOIN PRACOWNICY p
ON p.ID_SZEFA=sz.ID_PRAC
GROUP BY sz.NAZWISKO
ORDER BY LICZBA DESC;
-- 12
SELECT p.NAZWISKO, p.ZATRUDNIONY, 
  sz.NAZWISKO, sz.ZATRUDNIONY
FROM PRACOWNICY p
JOIN PRACOWNICY sz
ON sz.ID_PRAC=p.ID_SZEFA
WHERE DATEDIFF(p.ZATRUDNIONY, sz.ZATRUDNIONY)<=3650;
-- 13
-- ORACLE VERSION
SELECT PRACOWNICY.ETAT
FROM PRACOWNICY
WHERE YEAR(PRACOWNICY.ZATRUDNIONY)=1992
INTERSECT
SELECT PRACOWNICY.ETAT
FROM PRACOWNICY
WHERE YEAR(PRACOWNICY.ZATRUDNIONY)=1993;
-- 14
-- SELECT ZESPOLY.ID_ZESP, COUNT(*) AS LICZBA
-- FROM ZESPOLY
-- LEFT JOIN PRACOWNICY ON PRACOWNICY.ID_ZESP=ZESPOLY.ID_ZESP
-- GROUP BY ZESPOLY.ID_ZESP;
