-- 1
SELECT PRACOWNICY.NAZWISKO, 
  PRACOWNICY.ETAT, PRACOWNICY.ID_ZESP,
  ZESPOLY.NAZWA
FROM PRACOWNICY
JOIN ZESPOLY
WHERE PRACOWNICY.ID_ZESP=ZESPOLY.ID_ZESP;
-- 2
SELECT PRACOWNICY.NAZWISKO, PRACOWNICY.ETAT,
  PRACOWNICY.ID_ZESP, ZESPOLY.ADRES
FROM PRACOWNICY
JOIN ZESPOLY
ON PRACOWNICY.ID_ZESP=ZESPOLY.ID_ZESP
WHERE ZESPOLY.ADRES='PIOTROWO 3A'
ORDER BY NAZWISKO;