-- 1
SELECT PRACOWNICY.NAZWISKO, 
  PRACOWNICY.ETAT, PRACOWNICY.ID_ZESP,
  ZESPOLY.NAZWA
FROM PRACOWNICY
JOIN ZESPOLY
WHERE PRACOWNICY.ID_ZESP=ZESPOLY.ID_ZESP;
-- 2
SELECT PRACOWNICY.NAZWISKO, PRACOWNICY.ETAT,
  PRACOWNICY.ID_ZESP, ZESPOLY.ADRES
FROM PRACOWNICY
JOIN ZESPOLY
ON PRACOWNICY.ID_ZESP=ZESPOLY.ID_ZESP
WHERE ZESPOLY.ADRES='PIOTROWO 3A'
ORDER BY PRACOWNICY.NAZWISKO;
-- 3
SELECT PRACOWNICY.NAZWISKO, ZESPOLY.ADRES, ZESPOLY.NAZWA
FROM PRACOWNICY
JOIN ZESPOLY
ON PRACOWNICY.ID_ZESP=ZESPOLY.ID_ZESP
WHERE PRACOWNICY.PLACA_POD>400;
-- 4
SELECT PRACOWNICY.NAZWISKO, PRACOWNICY.PLACA_POD,
  ETATY.NAZWA, ETATY.PLACA_MIN, ETATY.PLACA_MAX
FROM PRACOWNICY
JOIN ETATY
ON ETATY.NAZWA=PRACOWNICY.ETAT;
-- 5
SELECT PRACOWNICY.NAZWISKO, PRACOWNICY.PLACA_POD, 
  PRACOWNICY.ETAT, ETATY.NAZWA, 
  ETATY.PLACA_MIN, ETATY.PLACA_MAX
FROM PRACOWNICY
JOIN ETATY
ON ETATY.NAZWA='SEKRETARKA'
WHERE PRACOWNICY.PLACA_POD<ETATY.PLACA_MAX 
AND PRACOWNICY.PLACA_POD>ETATY.PLACA_MIN;
-- 6
SELECT PRACOWNICY.NAZWISKO, PRACOWNICY.ETAT, 
  PRACOWNICY.PLACA_POD, ZESPOLY.NAZWA
FROM PRACOWNICY
JOIN ZESPOLY
ON PRACOWNICY.ID_ZESP=ZESPOLY.ID_ZESP
WHERE PRACOWNICY.ETAT!='ASYSTENT'
ORDER BY PRACOWNICY.PLACA_POD DESC;
-- 7
SELECT PRACOWNICY.NAZWISKO, PRACOWNICY.ETAT, 
  PRACOWNICY.PLACA_POD*12 + COALESCE(PRACOWNICY.PLACA_DOD,0) AS ROCZNA_PLACA, 
  ETATY.NAZWA, ZESPOLY.NAZWA
FROM PRACOWNICY
JOIN ZESPOLY ON ZESPOLY.ID_ZESP=PRACOWNICY.ID_ZESP
JOIN ETATY ON ETATY.NAZWA=PRACOWNICY.ETAT
WHERE PRACOWNICY.PLACA_POD*12 + COALESCE(PRACOWNICY.PLACA_DOD,0) >5500;
-- 8
SELECT p.ID_PRAC, p.NAZWISKO, sz.ID_PRAC, sz.NAZWISKO
FROM PRACOWNICY p
JOIN PRACOWNICY sz ON p.ID_SZEFA=sz.ID_PRAC;
