-- 1
SELECT NAZWISKO, ETAT, ID_ZESP
FROM PRACOWNICY
WHERE ID_ZESP=(SELECT ID_ZESP FROM PRACOWNICY WHERE NAZWISKO='BRZEZINSKI');
-- 2
SELECT NAZWISKO, ETAT, ZATRUDNIONY
FROM PRACOWNICY
WHERE ZATRUDNIONY=
  (SELECT MIN(ZATRUDNIONY)
    FROM PRACOWNICY
    WHERE ETAT='PROFESOR')
AND ETAT='PROFESOR';
-- 3
SELECT NAZWISKO, ZATRUDNIONY, ID_ZESP
FROM PRACOWNICY
WHERE (ZATRUDNIONY, ID_ZESP) IN
  (SELECT MAX(ZATRUDNIONY), ID_ZESP
    FROM PRACOWNICY
    GROUP BY ID_ZESP);
-- 4
-- 5
  SELECT NAZWISKO, PLACA_POD, ETAT
  FROM PRACOWNICY p
  WHERE p.PLACA_POD>
  (SELECT AVG(PLACA_POD)
    FROM PRACOWNICY
    WHERE p.ETAT=ETAT);
-- 6
  SELECT NAZWISKO, PLACA_POD
  FROM PRACOWNICY p
  WHERE p.PLACA_POD=
    (SELECT PLACA_POD
      FROM PRACOWNICY sz 
      JOIN PRACOWNICY POD
      ON sz.ID_PRAC=POD.ID_SZEFA
      );
-- 7
SELECT NAZWISKO
FROM PRACOWNICY p
WHERE NOT EXISTS (
  SELECT ID_PRAC FROM PRACOWNICY
  WHERE ID_SZEFA=p.ID_PRAC AND ETAT='STAZYSTA')
AND p.ETAT='PROFESOR';

-- 8
SELECT *
FROM ZESPOLY Z
WHERE NOT EXISTS (
  SELECT ID_ZESP
  FROM PRACOWNICY P
  WHERE Z.ID_ZESP=P.ID_ZESP
);
-- 9
SELECT ID_ZESP, SUM(PLACA_POD) AS SUMA
FROM PRACOWNICY P
GROUP BY ID_ZESP
HAVING SUM(PLACA_POD)>=ALL(
  SELECT SUM(PLACA_POD)
  FROM PRACOWNICY
  GROUP BY ID_ZESP
);


-- 10
SELECT NAZWISKO, PLACA_POD
FROM PRACOWNICY

-- 11
