-- 1
SELECT NAZWISKO, ETAT, ID_ZESP
FROM PRACOWNICY
WHERE ID_ZESP=(SELECT ID_ZESP FROM PRACOWNICY WHERE NAZWISKO='BRZEZINSKI');
-- 2
SELECT NAZWISKO, ETAT, ZATRUDNIONY
FROM PRACOWNICY
WHERE ZATRUDNIONY=
  (SELECT MIN(ZATRUDNIONY)
    FROM PRACOWNICY
    WHERE ETAT='PROFESOR')
AND ETAT='PROFESOR';
-- 3
SELECT NAZWISKO, ZATRUDNIONY, ID_ZESP
FROM PRACOWNICY
WHERE (ZATRUDNIONY, ID_ZESP) IN
  (SELECT MAX(ZATRUDNIONY), ID_ZESP
    FROM PRACOWNICY
    GROUP BY ID_ZESP);
  -- 4
  -- 5
  SELECT NAZWISKO, PLACA_POD, ETAT
  FROM PRACOWNICY p
  WHERE p.PLACA_POD>
  (SELECT AVG(PLACA_POD)
    FROM PRACOWNICY
    WHERE p.ETAT=ETAT);
  -- 6
  SELECT NAZWISKO, PLACA_POD
  FROM PRACOWNICY p
  WHERE p.PLACA_POD=
    (SELECT PLACA_POD
      FROM PRACOWNICY sz 
      JOIN PRACOWNICY POD
      ON sz.ID_PRAC=POD.ID_SZEFA
      );