-- ORACLE VERSION

CREATE TABLE PROJEKTY (
		ID_PROJEKTU NUMBER(4) CONSTRAINT PROJEKTY_PK PRIMARY KEY,
		OPIS_PROJEKTU VARCHAR(20) NOT NULL CONSTRAINT UNIQUE ,
		DATA_ROZPOCZECIA DATE DEFAULT SYSDATE
		DATA_ZAKONCZENIA DATE, 
		CONSTRAINT PROJEKTY_DATY_CHK CHECK( DATA_ZAKONCZENIA>DATA_ROZPOCZECIA),
		FUNDUSZ NUMBER(7,2) CONSTRAINT PROJEKTY_FUNDUSZ_CHK CHECK (FUNDUSZ>0)
	);

CREATE TABLE PRZYDZIALY
	(
		ID_PROJEKTU NUMBER(4) CONSTRAINT PRZYDZIALY_FK_01 REFERENCES PROJEKTY(ID_PROJEKTU),
		NR_PRACOWNIKA NUMBER(6) NOT NULL,
		OD DATE DEFAULT SYSDATE,
		DO DATE DEFAULT , CONSTRAINT PRZYDZIALY_DATY_CHK CHECK DO>OD,
		STAWKA NUMBER(7,2) CONSTRAINT PRZYDZIALY_STAWKA_CHK CHECK STAWKA>0,
		ROLA VARCHAR(20) CONSTRAINT RZYDZIALY_ROLA_CHK CHECK (ROLA IN ('ANALITYK', 'KIERUJACY', 'PROGRAMISTA')),
		CONSTRAINT PRZYDZIALY_PK PRIMARY KEY (ID_PROJEKTU, NR_PRACOWNIKA)
	);
ALTER TABLE PRZYDZIALY
ADD GODZINY NUMBER(4);

COMMENT ON TABLE PROJEKTY IS 'Lista projektów prowadzonych przez pracowników';  
COMMENT ON TABLE PRZYDZIALY IS 'Informacje o przydziale poszczególnych pracowników do projektów';
USER_CONSTRAINTS;

ALTER TABLE projekty
DISABLE UNIQUE(OPIS_PROJEKTU);

ALTER TABLE PROJEKTY
MODIFY (OPIS_PROJEKTU NUMBER(30));


CREATE TABLE PRACOWNICY_ZESPOLY
(NAZWISKO, POSADA, ROCZNA_PLACA, ZESPOL, ADRES_PRACY)
AS SELECT NAZWISKO, POSADA, PLACA_POD*12+COALESCE(PLACA_DOD, 0), NAZWA, ADRES 
FROM PRACOWNICY
JOIN ZESPOLY ON PRACOWNICY.ID_ZESP=ZESPOLY.ID_ZESP;

ALTER TABLE projekty
ENABLE UNIQUE(OPIS_PROJEKTU);